config/routes.rb
Rails.application.routes.draw do
  resources :productify_lists do
  		resources :productify_tasks do
  			member do
  				patch :complete
  			end
  		end
  end


  root 'productify_lists#index'
end

app/models/productify_list.rb
class ProductifyList < ActiveRecord::Base
	has_many :productify_tasks
end

app/models/productify_task.rb
class ProductifyTask < ActiveRecord::Base
  belongs_to :productify_list

  def completed?
  	!completed_at.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/productify_lists_controller.rb
class ProductifyListsController < ApplicationController
  before_action :set_productify_list, only: [:show, :edit, :update, :destroy]

  # GET /productify_lists
  # GET /productify_lists.json
  def index
    @productify_lists = ProductifyList.all
  end

  # GET /productify_lists/1
  # GET /productify_lists/1.json
  def show
  end

  # GET /productify_lists/new
  def new
    @productify_list = ProductifyList.new
  end

  # GET /productify_lists/1/edit
  def edit
  end

  # POST /productify_lists
  # POST /productify_lists.json
  def create
    @productify_list = ProductifyList.new(productify_list_params)

    respond_to do |format|
      if @productify_list.save
        format.html { redirect_to @productify_list, notice: 'Productify list was successfully created.' }
        format.json { render :show, status: :created, location: @productify_list }
      else
        format.html { render :new }
        format.json { render json: @productify_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productify_lists/1
  # PATCH/PUT /productify_lists/1.json
  def update
    respond_to do |format|
      if @productify_list.update(productify_list_params)
        format.html { redirect_to @productify_list, notice: 'Productify list was successfully updated.' }
        format.json { render :show, status: :ok, location: @productify_list }
      else
        format.html { render :edit }
        format.json { render json: @productify_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productify_lists/1
  # DELETE /productify_lists/1.json
  def destroy
    @productify_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Productify list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_productify_list
      @productify_list = ProductifyList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def productify_list_params
      params.require(:productify_list).permit(:title, :description)
    end
end

app/controllers/productify_tasks_controller.rb
class ProductifyTasksController < ApplicationController
	before_action :set_productify_list
	before_action :set_productify_task, except: [:create]

	def create
		@productify_task = @productify_list.productify_tasks.create(productify_task_params)
		redirect_to @productify_list
	end

	def destroy
		#@productify_task = @productify_list.productify_tasks.find(params[:id])
		if @productify_task.destroy
			flash[:success] = "Task was deleted!"
		else
			flash[:danger] = "Task was not deleted"
		end
		redirect_to @productify_list
	end

	def complete
		@productify_task.update_attribute(:completed_at, Time.now)
		redirect_to @productify_list, notice: "Task Completed"
	end

	private
		def set_productify_list
			@productify_list = ProductifyList.find(params[:productify_list_id])
		end

		def set_productify_task
			@productify_task = @productify_list.productify_tasks.find(params[:id])
		end

		def productify_task_params
			params[:productify_task].permit(:content)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productify_lists_helper.rb
module ProductifyListsHelper
end

app/helpers/productify_tasks_helper.rb
module ProductifyTasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Productify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/productify_lists/_form.html.erb
<%= form_for(@productify_list) do |f| %>
  <% if @productify_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@productify_list.errors.count, "error") %> prohibited this productify_list from being saved:</h2>

      <ul>
      <% @productify_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productify_lists/edit.html.erb
<h1 class="productify_list_title">Edit List</h1>

<div class="form">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Cancel', productify_lists_path %>
</div>

app/views/productify_lists/index.html.erb
<% @productify_lists.each do |productify_list|%>
  <div class="index_row clearfix">
    <h2 class="productify_list_title"><%= link_to productify_list.title, productify_list %></h2>
    <p class="productify_list_sub_title"><%= productify_list.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "New Productify List", new_productify_list_path %>
</div>

app/views/productify_lists/new.html.erb
<h1 class="productify_list_title">New List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Back', productify_lists_path %>
</div>

app/views/productify_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h4 class="productify_list_title"><%= @productify_list.title %></h4>
<p class="productify_list_sub_title"><%= @productify_list.description %></p>


<div id="productify_tasks_wrapper">
	<%= render @productify_list.productify_tasks %>
	<div id="form">
		<%= render "productify_tasks/form" %>
	</div>
</div>

<div class="links">
	<%= link_to 'Edit', edit_productify_list_path(@productify_list) %> |
	<%= link_to 'Back', productify_lists_path %> |
	<%= link_to 'Delete', productify_list_path(@productify_list), method: :delete, data: { confirm: "Are you sure"} %>
</div>

app/views/productify_tasks/_form.html.erb
<%= form_for([@productify_list, @productify_list.productify_tasks.build]) do |f| %> 

	<%= f.text_field :content, placeholder: "New Task" %>
	<%= f.submit %>

<% end %>

app/views/productify_tasks/_productify_task.html.erb
<div class="row clearfix">
	
	<% if productify_task.completed? %>
		<div class="complete">
			<%= link_to complete_productify_list_productify_task_path(@productify_list, productify_task.id), method: :patch do %>
				<i style="opacity: 0.6;" class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="productify_task">
			<p style="opacity: 0.4; "><strike><%= productify_task.content %></strike></p>
		</div>
		<div class="trash">
			<%= link_to productify_list_productify_task_path(@productify_list, productify_task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i style="opacity: 0.6;" class="fa fa-trash"></i>
			<% end %>
		</div>
	<% else %>
		<div class="complete">
			<%= link_to  complete_productify_list_productify_task_path(@productify_list, productify_task.id), method: :patch do %>
				<i class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="productify_task">
			<p><%= productify_task.content %></p>
		</div>
		<div class="trash">
			<%= link_to productify_list_productify_task_path(@productify_list, productify_task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>

	<% end %>

</div>